development:
  adapter: mysql2
  encoding: utf8
  database: access_education_development
  pool: 5
  username: root
  password:
  reconnect: false
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: access_education_test
  pool: 5
  reconnect: false
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  url: <%= ENV['DATABASE_URL'] %>
  pool: 15
